### ISSUE TITLE
Theme like demo mrbsdemo.uk.to

### ISSUE THREAD

**Issue by pellou82** [meeting-room-booking-system/mrbs-code#3579]
Hi,

thanks for sharing this amazing tool, But I was wondering if there was the possibility of having the same theme as shown into the demo m.rbsdemo.uk.to

Thanks

**Comment by campbell-m** [comment]
Can you post a screenshot please?

**Comment by campbell-m** [comment]
You need to upgrade to the latest version to get the same them as the demo.  MRBS 1.4.9 is a very old version of MRBS.

**Comment by pellou82** [comment]
Hi the mysql version is 8.0 the php 8.2

**Comment by campbell-m** [comment]
And what are `$auth['type']` and `$auth['session']` set to?

**Comment by pellou82** [comment]
Finally, I installed the mrbs 1.9.0 on this website:
https://pelloztest.altervista.org/web
during the DB setup I get always the error indicated before, but seems to work properly.

**Comment by campbell-m** [comment]
I expect you are getting that error because the table 'mrbs_area' already exists, as you say.  But why did you install MRBS 1.9.0 and not the latest version?

**Comment by pellou82** [comment]
I was trying which version I was able to install, and after several attempts, I was not able to install after version 1.10.0... and I don't understand why....

**Comment by campbell-m** [comment]
What were the errors you were getting when trying to install the latest version (1.11.4)?

**Comment by pellou82** [comment]
I am having problems from 1.11.1 to 1.11.4... but not with the 1.10.0. With these I don't see the calendars.. I you want, I can install on a demo site.. and you can check

**Comment by campbell-m** [comment]
Yes please, can you install 1.11.4 on a demo site?  Also, when you install 1.11.4 are you getting any error messages when you create the database tables?

**Comment by pellou82** [comment]
the error is always the same.. about the mrbs_area. 
https://brtweb.altervista.org/web

This is the demo 1.11.4 it all yours. :)

**Comment by campbell-m** [comment]
I suspect the problem is that you are not creating the tables properly.  You are getting the message about mrbs_area because it already exists.  Try using a different prefix, eg "mrbs2_".  Edit tables.my.sql and do a global replace of "mrbs_" by "mrbs2_".  Then change `$tbl_prefix` in your config file so that it is set to "mrbs2_".

**Comment by pellou82** [comment]
how can i do this?
II was trying 
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/8396225/b2dae1a9-0d33-4bca-b7cf-138c5bab49be)
but nothing happens

**Comment by campbell-m** [comment]
You need to edit tables.my.sql in an editor, eg Notepad++, before executing the SQL.

**Comment by pellou82** [comment]
Done, check it now

**Comment by campbell-m** [comment]
Thanks.  Still the same problem.  Can you post a screenshot from phpMyAdmin of the structure of your mrbs2_sessions table?

**Comment by pellou82** [comment]
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/8396225/06d7aa47-2b0e-45cf-b101-6ec4a2ac7440)

**Comment by campbell-m** [comment]
The table looks OK.  I don't understand what's going wrong.  For some reason you are getting the error

~~~text
session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /membri/.dummy/temp)
~~~

in MRBS 1.11.0 and above.  I will need to think about it.

**Comment by pellou82** [comment]
many thanks for your time, I think that using the 1.10.0 will be able to do all I need.... I hope that I have helped you to find an issue. 
Best!!

**Comment by campbell-m** [comment]
On your 1.11.4 test system (http://brtweb.altervista.org/web/) could you please replace lib/MRBS/SessionHandlerDb.php with the attached diagnostic version?  You'll need to unzip the attachment first.
[SessionHandlerDb.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/13628512/SessionHandlerDb.zip)

**Comment by pellou82** [comment]
Done: 
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/8396225/e740e0df-f02a-41bc-88a3-a49ea93a7075)

**Comment by campbell-m** [comment]
Thanks.  It looks like my theory was wrong as your system does support multiple locks.  Point 2 is therefore not relevant.

I've created some more diagnostics.  On your 1.11.4 test system (http://brtweb.altervista.org/web/) could you please replace lib/MRBS/Session/Session.php with the attached diagnostic version? You'll need to unzip the attachment first.

[Session.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/13650331/Session.zip)

**Comment by pellou82** [comment]
Done.

If you want more informations regardings this free hosting that could help, tell me.

Best

**Comment by campbell-m** [comment]
> If you want more informations regardings this free hosting that could help, tell me.

Yes, please, that would be useful.

**Comment by campbell-m** [comment]
I've signed up for a free Altervista account and am waiting for the activation details.

**Comment by pellou82** [comment]
You are Amazing! In 24hrs you Will receive everything. In case of problems, you can use my subdomain.

**Comment by campbell-m** [comment]
I have found what is causing the problem: it seems that the Altervista PHP/MySQL platform isn't respecting the `PDO::MYSQL_ATTR_FOUND_ROWS` option.  This is used when executing an `UPDATE` query.  Normally `rowCount()` after an `UPDATE` will just tell you how many rows were _changed_.  But if you set `PDO::MYSQL_ATTR_FOUND_ROWS` to `true` it should tell you how many rows were _found_, whether or not they were changed.  However on Altervista this option is being ignored.  This can be demonstrated by the following test program (designed to be run in the MRBS directory):

~~~php
<?php

error_reporting(-1);
ini_set('display_errors', '1');

require 'config.inc.php';

$dsn = "mysql:dbname=$db_database;host=$db_host";
$options = [PDO::MYSQL_ATTR_FOUND_ROWS => true];

$dbh = new PDO($dsn, $db_login, $db_password, $options);

$sql = "INSERT IGNORE INTO mrbs_sessions (id, access, data) VALUES ('1234', 1, 'test')";
$stmt = $dbh->prepare($sql);
$stmt->execute();

$sql = "UPDATE mrbs_sessions SET access=1 WHERE id='1234'";
$stmt = $dbh->prepare($sql);
$stmt->execute();

echo $stmt->rowCount();
~~~

The output should be '1', but on Altervista it is '0'.

In the short term you can get MRBS 1.11.0 and later working on Altervista by editing the method `updateTimestamp()` in the file lib/MRBS/SessionHandlerDb.php and changing the line 245 (roughly, depending on version) from

~~~php
      $result = (1 === db()->command($sql, $sql_params));
~~~

to

~~~php
      $result = true;
~~~

This isn't ideal as they may be other places where MRBS relies on knowing the number of rows found.  I will raise an issue on the Altervista forum.

**Comment by pellou82** [comment]
Wow. Do you know a free hosting that can be used?
Thanks a lot for your support!

**Comment by campbell-m** [comment]
> I will raise an issue on the Altervista forum.

I have raised [this issue](https://forum.it.altervista.org/problemi-tecnici-account/294103-problema-con-pdo-mysql_attr_found_rows.html) on the Altervista forum.

**Comment by campbell-m** [comment]
> Do you know a free hosting that can be used?

Sorry, I don't.

**Comment by campbell-m** [comment]
As you'll see above, I've also fixed a couple of issues that were generating NOTICE errors on Altervista.

**Comment by campbell-m** [comment]
And I've also posted in the Altervista forum [here](https://forum.it.altervista.org/php-mysql-e-apache-htaccess/294104-problema-con-pdo-mysql_attr_found_rows.html#post1490443).  (Apologies to Altervista for double-posting but I think I posted in the wrong section the first time.)

**Comment by campbell-m** [comment]
I have also [posted on StackOverflow](https://stackoverflow.com/questions/77671522/why-is-pdomysql-attr-found-rows-not-working).

**Comment by pellou82** [comment]
Seems that ok Altervista they dont answer you... I Hope that on stackoverflow they will give you more info.

**Comment by campbell-m** [comment]
[Some progress](https://forum.it.altervista.org/php-mysql-e-apache-htaccess/294104-problema-con-pdo-mysql_attr_found_rows.html#post_1490454) from Altervista.

**Comment by pellou82** [comment]
Great news!
